# Generated by Django 2.1 on 2018-10-03 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_series', models.CharField(max_length=50)),
                ('car_series_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='Invalid year', message='Year must be a four digit number', regex='[0-9]{4}')])),
                ('car_price_new', models.IntegerField()),
                ('car_engine_size', models.CharField(max_length=50)),
                ('car_fuel_system', models.CharField(max_length=50)),
                ('car_tank_capacity', models.CharField(max_length=50)),
                ('car_power', models.CharField(max_length=50)),
                ('car_seating_capacity', models.IntegerField()),
                ('car_standard_transmission', models.CharField(max_length=50)),
                ('car_body_type', models.CharField(max_length=50)),
                ('car_drive', models.CharField(max_length=50)),
                ('car_wheelbase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_birthday', models.DateField()),
                ('customer_occupation', models.CharField(max_length=50)),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('order_create_date', models.CharField(max_length=50)),
                ('order_pickup_date', models.CharField(max_length=50)),
                ('order_pickup_store', models.IntegerField()),
                ('pickup_store_name', models.CharField(max_length=50)),
                ('pickup_store_address', models.CharField(max_length=50)),
                ('pickup_store_phone', models.CharField(max_length=50)),
                ('pickup_store_city', models.CharField(max_length=50)),
                ('pickup_store_state', models.CharField(max_length=50)),
                ('order_return_date', models.CharField(max_length=50)),
                ('order_return_store', models.IntegerField()),
                ('return_store_name', models.CharField(max_length=50)),
                ('return_store_address', models.CharField(max_length=50)),
                ('return_store_phone', models.CharField(max_length=50)),
                ('return_store_city', models.CharField(max_length=50)),
                ('return_store_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('store_address', models.CharField(max_length=50)),
                ('store_phone', models.CharField(max_length=50)),
                ('store_city', models.CharField(max_length=50)),
                ('store_state', models.CharField(max_length=50)),
            ],
        ),
    ]
