# Generated by Django 2.1.1 on 2018-10-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_birthday',
            field=models.CharField(max_length=50),
        ),
    ]
