# Generated by Django 2.1.1 on 2018-10-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180911_2244'),
        ('search', '0002_auto_20181003_1912'),
    ]

    operations = [
    ]
