# Generated by Django 2.1 on 2018-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_series', models.CharField(max_length=50)),
                ('car_series_year', models.IntegerField()),
                ('car_price_new', models.IntegerField()),
                ('car_engine_size', models.CharField(max_length=50)),
                ('car_fuel_system', models.CharField(max_length=50)),
                ('car_tank_capacity', models.CharField(max_length=50)),
                ('car_power', models.CharField(max_length=50)),
                ('car_seating_capacity', models.IntegerField()),
                ('car_standard_transmission', models.CharField(max_length=50)),
                ('car_body_type', models.CharField(max_length=50)),
                ('car_drive', models.CharField(max_length=50)),
                ('car_wheelbase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_birthday', models.DateField()),
                ('customer_occupation', models.CharField(max_length=50)),
                ('customer_gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_create_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('store_address', models.CharField(max_length=50)),
                ('store_phone', models.IntegerField()),
                ('store_city', models.CharField(max_length=50)),
                ('store_state', models.CharField(max_length=50)),
            ],
        ),
    ]
