# Generated by Django 2.1 on 2018-09-11 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180911_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_series_year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='Invalid year', message='Year must be a four digit number', regex='[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(max_length=50),
        ),
    ]
